### ISSUE TITLE
Trigger card not working

### ISSUE THREAD

**Issue by llentjes** [athombv/com.irobot.roomba980#24]
Trigger card "De status is veranderd naar " is not working.
Possible a language issue (the card is in dutch and the tag is english)

**Comment by RobinBol** [comment]
FYI, this should be fixed in com.irobot.roomba980@2.04 i.c.w. Homey v3.0.0.
------


Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Alternatively, use the 'Report an issue' button on the App page in the Homey Apps store to create an issue at the correct location. This issue will be closed now, our apologies for the inconvenience.
